#!/bin/bash

echo "Installing prerequisites..."

# INSTALL JAVA DEVELOPMENT KIT
echo "Installing Java Development Kit..."
#sudo apt-get install default-jdk
echo "Finished installing Java Development Kit."

echo "Finished installing prerequisites."